# Generated by Django 2.1.2 on 2018-12-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20181212_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemiventario',
            name='contagem_01',
        ),
        migrations.RemoveField(
            model_name='itemiventario',
            name='contagem_02',
        ),
        migrations.RemoveField(
            model_name='itemiventario',
            name='contagem_03',
        ),
        migrations.AddField(
            model_name='itemiventario',
            name='contagem_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemiventario',
            name='contagem_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemiventario',
            name='contagem_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
