# Generated by Django 2.1.2 on 2018-12-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20181212_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemiventario',
            name='contagem_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemiventario',
            name='contagem_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemiventario',
            name='contagem_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
