# Generated by Django 2.1.2 on 2018-12-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='complemento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='nome_do_logradouro',
            field=models.CharField(max_length=50, verbose_name='nome do logradouro'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='nome_fantasia',
            field=models.CharField(max_length=60, verbose_name='nome fantasia'),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='razao_social',
            field=models.CharField(max_length=60, verbose_name='razão social'),
        ),
    ]
