# Generated by Django 2.1.2 on 2018-12-12 02:00

from django.db import migrations, models
import django.db.models.deletion
import estocagem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosiçãodeEstocagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_setor', estocagem.models.UpperCaseCharField(blank=True, help_text='Atenção, valor deve ser único', max_length=8, unique=True, verbose_name='endereço do setor')),
                ('nome_posicao', models.CharField(blank=True, max_length=20, verbose_name='nome/descrição do endereço')),
                ('tipo_saida', models.CharField(choices=[('1', 'INDIFERENTE'), ('2', 'VENCIMENTO'), ('3', 'PEPS'), ('4', 'UEPS')], default=1, max_length=2, verbose_name='tipo de saída do material')),
            ],
            options={
                'verbose_name': 'Posição de estocagem',
                'verbose_name_plural': 'Posições de estocagem',
            },
        ),
        migrations.CreateModel(
            name='VinculaPosicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Material')),
                ('posicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='estocagem.PosiçãodeEstocagem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vinculaposicao',
            unique_together={('posicao', 'material')},
        ),
    ]
